name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js et installation de PNPM
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Utilise une version compatible de Node.js
          cache: 'pnpm'     # Active le cache PNPM pour accélérer les builds futurs

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Build project
        run: |
          pnpm build

      - name: Deploy to GitHub Pages
        run: |
          pnpm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
